stages:
  - check
  - deploy
check_index:
  stage: check
  script:
    - |
      if [ ! -f public/index.html ]; then
        echo "Erro: public/index.html não encontrado."
        exit 1
      fi
pages:
  stage: deploy
  script:
    - echo "Publicando página..."
  artifacts:
    paths:
      - public
  only:
    - main
